board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.boardRedirection, name=''),
    path('<int:course_id>/', views.BoardView.as_view(), name='board'),
    path('<int:course_id>/new_post/', views.NewPost.as_view(), name='new_post'),
    path('post/<int:post_id>/edit_post', views.EditPost.as_view(), name='edit_post'),
    path('post/<int:post_id>/delete_post', views.DeletePost.as_view(), name='delete_post'),
    path('post/<int:post_id>', views.PostView.as_view(), name='post'),
    path('post/<int:post_id>/like/', views.PostView.as_view(), name='post_like'),
]

user/urls.py
from django.conf.urls import url
from . import views

app_name = 'user'
urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^profile/$', views.view_profile, name='profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
]

yanadok/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('timetable.urls')),
    path('course/', include('course.urls')),
    path('', TemplateView.as_view(template_name='timetable/timetable.html'), name='home'),
    path(r'board/', include('board.urls', namespace='board')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
]

templates/base.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static "common.css" %}">
  <title>{% block title %}야나독{% endblock %}</title>
    {% block head %}
    {% endblock %}
</head>
<body>
  <main>
      {% block content %}
      {% endblock %}
  </main>
</body>
</html>

templates/nav.html
{% block head %}
{% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "nav.css" %}">
{% endblock %}


<nav class="navbar bg-primary">
    <div class="nav-logo">
        <a href="/">
            <img src="{% static "img/home.png" %}" width="100%" height="100%"/>
        </a>
    </div>
    <div class="right-area">
        <span class="encourage text-white">야 너도 할수있어 독강</span>
        <div id="logout text-white">
          <p><a class="text-white" href="{% url 'logout' %}">로그아웃</a></p>
        </div>
    </div>
</nav>

templates/nav2.html
{% block head %}
{% load staticfiles %}
 <link rel="stylesheet" type="text/css" href="{% static "nav2.css" %}">
{% endblock %}

<nav class="navbar navbar-expand-md fixed-top" style="background-color: #8578d2;">

        <div class="nav-logo"><a href="/"><img src="{% static "img/home.png" %}" width="100%" height="100%"/></a></div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        강의목록
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                        {% for course in course_list %}
                        <a class="dropdown-item" href="{% url 'board:board' course.course_id %}">{{course.course_name}}</a>
                        <div class="dropdown-divider"></div>
                        {% endfor %}
                        {% endif %}
                    </div>
                </li>
            </ul>
            <span class="navbar-text">
               {% if user.is_authenticated %}
               <a href="{% url 'user:profile' %}">{{user.username}}</a>
               <a href="{% url 'logout' %}">Logout</a>
               {% endif %}
           </span>
        </div>

</nav>