board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.boardRedirection, name=''),
    path('<int:course_id>/', views.BoardView.as_view(), name='board'),
    path('<int:course_id>/new_post/', views.NewPost.as_view(), name='new_post'),
    path('post/<int:post_id>/edit_post', views.EditPost.as_view(), name='edit_post'),
    path('post/<int:post_id>/delete_post', views.DeletePost.as_view(), name='delete_post'),
    path('post/<int:post_id>', views.PostView.as_view(), name='post'),
    path('post/<int:post_id>/like/', views.PostView.as_view(), name='post_like'),
]

user/urls.py
from django.conf.urls import url
from . import views

app_name = 'user'
urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^profile/$', views.view_profile, name='profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
]

yanadok/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('timetable.urls')),
    path('course/', include('course.urls')),
    path('', TemplateView.as_view(template_name='timetable/timetable.html'), name='home'),
    path(r'board/', include('board.urls', namespace='board')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
]

board/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    BOARD_CHOICES = (
        ('공지사항', '공지사항'),
        ('스터디/팀플', '스터디/팀플'),
    )
    post_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey('user.User', models.DO_NOTHING, db_column='user_id', blank=True, null=True)
    course = models.ForeignKey('course.Course', models.DO_NOTHING, db_column='course_id', blank=True, null=True)
    title = models.CharField(max_length=20, blank=True, null=True)
    password = models.CharField(max_length=20, blank=True, null=True)
    content = models.TextField()
    post_type = models.CharField(max_length=10, default='공지사항', choices=BOARD_CHOICES)
    is_closed = models.DateTimeField(blank=True, null=True)
    upload_time = models.DateTimeField(default=timezone.now())

    class Meta:
        db_table = 'post'


class PostLike(models.Model):
    post_like_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey('user.User', models.DO_NOTHING, db_column='user_id', blank=True, null=True)
    post_id = models.ForeignKey(Post, models.DO_NOTHING, db_column='post_id', blank=True, null=True)

    class Meta:
        db_table = 'post_like'
        unique_together = (('user_id', 'post_id'),)


class Comment(models.Model):
    comment_id = models.AutoField(primary_key=True)
    post_id = models.ForeignKey('board.Post', models.DO_NOTHING, db_column='post_id', blank=True, null=True)
    user_id = models.ForeignKey('user.User', models.DO_NOTHING, db_column='user_id', blank=True, null=True)
    comment_content = models.TextField()
    upload_time = models.DateTimeField(default=timezone.now())

    class Meta:
        db_table = 'comment'

board/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['post_type', 'title', 'content', ]



class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment_content', ]

board/views.py
from django.shortcuts import redirect

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic

from course.models import Course
from timetable.models import Timetable
from .models import Post, Comment, PostLike
from django.apps import apps
from .forms import PostForm

from django.shortcuts import render


from . import dao

course = apps.get_model('course', 'Course')
user = apps.get_model('user', 'User')


class BoardView(generic.View):

    def get(self, request, course_id):
        course_list = []
        for lecture in Timetable.objects.filter(user_id=request.user.id):
            course_list.append(Course.objects.get(course_id=lecture.course.course_id))

        template = loader.get_template('board/board.html')
        user_id = request.user.id

        posts = Post.objects.filter(course_id=course_id).order_by('upload_time')

        course_idlist = []

        notice_posts = dao.select_notice_posts(course_id)
        current_course = Course.objects.get(course_id=course_id)
        context = {
            'course_id': course_id,
            'current_course': current_course,
            'posts': posts,
            'notice_posts': notice_posts,
            'course_idlist': course_idlist,
            'course_list': course_list,
        }

        return HttpResponse(template.render(context, request))

    def post(self, request, course_id):
        course_list = []
        for lecture in Timetable.objects.filter(user_id=request.user.id):
            course_list.append(Course.objects.get(course_id=lecture.course.course_id))
        template = loader.get_template('board/board.html')
        userId = request.user.id

        if request.method == "POST":
            course_id = request.POST.get('course_id')
            post_type = request.POST.get('post_type')
            key_word = request.POST.get('kw')

        course_name = dao.get_course_name(course_id)

        if post_type == None:
            posts = dao.select_all_posts(course_id)
        elif post_type == '스터디팀플':
            posts = dao.select_study_posts(course_id)
        else:
            posts = dao.select_all_posts(course_id)

        if key_word != None:
            results = []
            for post in posts:
                if key_word in post['title']:
                    results.append(post)
            posts = results

        courselist = dao.get_courselist(userId)
        course_idlist = []
        current_course = Course.objects.get(course_id=course_id)

        for course in courselist:
            course_idlist.append(course['course_id'])

        notice_posts = dao.select_notice_posts(course_id)

        context = {
            'course_id': course_id,
            'current_course': current_course,
            'course_name': course_name,
            'posts': posts,
            'notice_posts': notice_posts,
            'courselist': courselist,
            'course_idlist': course_idlist,
            'post_type': post_type,
            'course_list': course_list,
        }

        return HttpResponse(template.render(context, request))


def boardRedirection(request):
    return HttpResponseRedirect(reverse('timetable:home'))


class NewPost(generic.View):

    def get(self, request, course_id):
        course_list = []
        for lecture in Timetable.objects.filter(user_id=request.user.id):
            course_list.append(Course.objects.get(course_id=lecture.course.course_id))
        template = 'board/new_post.html'
        form = PostForm()
        return render(request, template, {'form': form, 'course_list': course_list, })

    def post(self, request, course_id):
        course_list = []
        for lecture in Timetable.objects.filter(user_id=request.user.id):
            course_list.append(Course.objects.get(course_id=lecture.course.course_id))
        template = 'board/new_post.html'
        form = PostForm(request.POST or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.user_id = request.user
            post.course_id = course_id
            post.save()
            return redirect('board:board', course_id)
        else:
            form = PostForm()
        return render(request, template, {'form': form, 'course_list': course_list, })


class EditPost(generic.View):

    def get(self, request, post_id):
        course_list = []
        for lecture in Timetable.objects.filter(user_id=request.user.id):
            course_list.append(Course.objects.get(course_id=lecture.course.course_id))
        template = 'board/new_post.html'
        posting = Post.objects.get(post_id=post_id)
        if posting.user_id != request.user:
            return HttpResponse('잘못된 접근입니다.')
        form = PostForm(instance=posting)
        return render(request, template, {'form': form, 'course_list': course_list, })

    def post(self, request, post_id):
        course_list = []
        for lecture in Timetable.objects.filter(user_id=request.user.id):
            course_list.append(Course.objects.get(course_id=lecture.course.course_id))
        template = 'board/new_post.html'
        posting = Post.objects.get(post_id=post_id)
        course_id = posting.course_id
        form = PostForm(request.POST, instance=posting)
        if form.is_valid():
            post = form.save(commit=False)
            post.user_id = request.user
            post.course_id = course.objects.get(course_id=course_id)
            post.save()
            return redirect('board:post', post_id)
        else:
            form = PostForm(instance=posting)
        return render(request, template, {'form': form, 'course_list': course_list, })


class DeletePost(generic.View):

    def get(self, request, post_id):
        dpost = Post.objects.get(post_id=post_id)
        if dpost.user_id != request.user:
            return HttpResponse('잘못된 접근입니다.')
        course_id = dpost.course_id
        Comment.objects.filter(post_id=post_id).delete()
        dpost.delete()
        return HttpResponseRedirect(reverse('board:board', args=(course_id,)))


class PostView(generic.View):
    def get(self, request, post_id):
        course_list = []
        for lecture in Timetable.objects.filter(user_id=request.user.id):
            course_list.append(Course.objects.get(course_id=lecture.course.course_id))
        template = loader.get_template('board/post.html')

        post = Post.objects.get(post_id=post_id)
        like_num = PostLike.objects.filter(post_id=post_id).count
        course_id = post.course_id

        user_id = request.user.id
        like_active = dao.like_active(post_id, user_id)
        if like_active == True:
            message = 'unlike'
            like_class = 'like_active'
        else:
            message = 'like'
            like_class = 'like'

        comment_list = Comment.objects.filter(post_id=post_id)

        context = {
            'user_id': user.objects.filter(id=user_id)[0],
            'post': post,
            'like_num': like_num,
            'message': message,
            'like_class': like_class,
            'course_id': course_id,
            'comment_list': comment_list,
            'course_list': course_list,
        }

        return HttpResponse(template.render(context, request))

    def post(self, request, post_id):
        course_list = []
        for lecture in Timetable.objects.filter(user_id=request.user.id):
            course_list.append(Course.objects.get(course_id=lecture.course.course_id))
        template = loader.get_template('board/post.html')
        message = ''
        like_class = ''
        user_id = request.user.id

        if request.method == "POST":
            like = request.POST.get('like')
            message = request.POST.get('message')
            comment_content = request.POST.get('comment_content')
            comment_action = request.POST.get('comment_action')


            if like == 'like_active':
                dao.delete_like(post_id, user_id)
                message = '좋아요'
                like_class = 'like'

            elif like == 'like':
                dao.insert_like(post_id, user_id)
                message = '좋아요 취소'
                like_class = 'like_active'

            if comment_action == 'insert':
                dao.insert_comment(post_id, user_id, comment_content)

            elif comment_action == 'delete':
                comment_id = int(request.POST.get('comment_id'))
                Comment.objects.get(comment_id=comment_id).delete()

        post = Post.objects.get(post_id=post_id)
        course_id = post.course_id
        like_num = PostLike.objects.filter(post_id=post_id).count
        comment_list = Comment.objects.filter(post_id=post_id)

        context = {
            'user_id': user.objects.filter(id=user_id)[0],
            'post': post,
            'like_num': like_num,
            'message': message,
            'like_class': like_class,
            'course_id': course_id,
            'comment_list': comment_list,
            'course_list': course_list,
        }

        return HttpResponse(template.render(context, request))

templates/board/new_post.html
{% extends 'base.html' %}
{% block head %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'board/new_post.css' %}">
{% endblock %}
{% block content %}
{% include "nav2.html" %}
<form method="post" >
    {% csrf_token %}
    <br>
    <br>
    <br>
    
    <div class="col">
        <div class="row justify-content-center">
            <div class="field box-type">
                <label for="id_post_type" class="label">게시판</label>
                <select name="post_type" id="id_post_type">
                    <option value="공지사항" selected="">공지사항</option>
                    <option value="스터디/팀플">스터디/팀플</option>
                </select>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="field box-title">
                <label for="id_title" class="label">제목</label>
                <input type="text" name="title" maxlength="20" id="id_title" class="input" value="{{form.title.value}}">
            </div>

        </div>
        <div class="row justify-content-center">
            <div class="field box-content">
                <label for="id_content" class="label">내용</label>
                <textarea name="content" cols="40" rows="10" required="" id="id_content" class="input">{{form.content.value}}</textarea>
            </div>

        </div>
        <div class="row justify-content-center">
            <div class="field box-submit">
                <button type="submit" class="btn btn-primary text-white">저장</button>
                <a href="javascript:history.back()" class="btn btn-primary text-white">취소</a>
            </div>
        </div>
</form>
{% endblock %}

templates/board/post.html
{% extends 'base.html' %}

{% block head %}
    {% load staticfiles %}
      {% load filters %}
      <script>
      $(document).ready(function(){
      $(document).on('click', '#like_btn', function(){
        var like = $('#like_btn').attr('class');
        $.ajax({
            type: "POST",
            url: "{% url 'board:post_like' post.post_id %}",
            data: {'like': like,
            'csrfmiddlewaretoken': '{{ csrf_token }}', },
            success: function(response) {
              $dom = $(document.createElement("html"));
              $dom[0].innerHTML = response;
              $body = $dom.find("#like_btn_wrapper")[0];
              $curDom = $('html');
              $div = $curDom.find("#like_container")[0];
              $($div).html($body);
              if (like == 'like_active') {
                $('#like_btn').removeClass('like_active');
                $('#like_btn').addClass('like');
               }
              else {
                $('#like_btn').removeClass('like');
                $('#like_btn').addClass('like_active');
              }
            }
         })
    })

    $(document).on('click', '#submit_comment_btn', function(){
        var comment_content = $('#comment_input').val();
        console.log("hi");

        $.ajax({
            type: "POST",
            url: '',
            data: {'comment_content': comment_content, 'comment_action': 'insert',
            'csrfmiddlewaretoken': '{{ csrf_token }}',},

            success: function(response) {
              $dom = $(document.createElement("html"));
              $dom[0].innerHTML = response;
              $body = $dom.find("#comment_wrapper");
              $curDom = $('html');
              $div = $curDom.find("#comment_container");
              $($div).html($body);
            }
         })
    })

    $(document).on('click', '.delete_comment_btn', function(){
        var index = $('html').find(".delete_comment_btn").index(this);
        var comment_id = $(this).attr("id");
        $.ajax({
            type: "POST",
            url: '',
            data: {'comment_action': 'delete', 'index': index, 'comment_id':comment_id,
            'csrfmiddlewaretoken': '{{ csrf_token }}',},


            success: function(response) {
              $dom = $(document.createElement("html"));
              $dom[0].innerHTML = response;
              $body = $dom.find("#comment_wrapper");
              $curDom = $('html');
              $div = $curDom.find("#comment_container");
              $($div).html($body);
            }
         })
    })
  });
    </script>
    <link rel="stylesheet" type="text/css" href="{% static 'board/post.css' %}?after">
{% endblock %}


{% block content %}
    {% include "nav2.html" %}
    <br>
    <br>
    <br>
    <br>
    <table align="center" cellpadding="0" width="990" style="margin-bottom:3px;">
        <tbody>
            <tr>
                <td width="650" style="padding-left:10px;padding-top:5px;" valign="middle" align="left" height="44">
                    <a href="">
                        <span style="color:#111;font-size:21px;" class="daum">{{post.post_type}}</span>
                    </a>
                    <br>
                    <span class="sm mbox" style="color:#848688;padding:5px 0;"></span>
                </td>
            </tr>
        </tbody>
    </table>


    <table align="center" border="0" cellspacing="6" cellpadding="6" width="986" style="margin-bottom:10px;border:1px solid rgb(234, 234, 234);">
        <tbody>
            <tr>
                <td valign="top" align="center" width="120">
                    <img src="{% static "img/hand.png" %}" title="프로필사진" style="max-width:100%;max-height:120px;border-radius:8px;">
                </td>
                <td valign="top" align="left" style="line-height:28px;">
                    <span class="daum" style="color:#333333;font-size:20px;">{{ post.title }}</span><br>
                    <span style="letter-spacing:0px;color:#8578d2;font-weight:bold;font-size:14px;" class="daum">{{ post.user_id }}</span><br>
                    <span style="font-size:12px;">{{ post.upload_time }} </span>
                </td>
            </tr>
        </tbody>
    </table>

    <table border="0" cellspacing="0" cellpadding="0" width="986" class="pic_bg" style="table-layout:fixed;">
        <tbody><tr><td width="100%" align="left" style="padding-top:15px;"></td></tr></tbody>
    </table>



    <table align="center" id="bonmoon" border="0" cellspacing="0" cellpadding="0" width="986" class="han_new " style="font-size:15px;padding:20px 18px 10px 18px;letter-spacing:-0.5px;">
        <tbody>
            <tr>
                <td valign="top">{{ post.content }}</td>
            </tr>
            <tr>
                <td>
                    <br>
                    <script type="text/javascript">

                        function update_chu_bbs(kbn,id, no) {

                            var url = "../bbs/bbschuu.php";

                            $.get(url, {kbn:kbn, id:id, no:no}, function(args) {

                                $("#div_chu_bbs").html(args);

                            });

                        }
                    </script>
                    <br>
                    <center>

                    </center>
                </td>
            </tr>
        </tbody>
    </table>

    <p>

    </p>
    <table align="center" width="970" cellspacing="0" cellpadding="5" style="margin-bottom:14px;margin-top:10px;">
        <tbody>
        <tr>
            <td height="26" width="50%" align="left">
                 <span id="div_chu_bbs">
                     <div id="like_container">
                         <div id="like_btn_wrapper">
                             <a class="{{ like_class }}" id="like_btn">좋아요 {{ like_num }}</a>

                         </div>
                     </div>
                 </span>
            </td>
            <td height="26" width="50%" align="right" style="padding-right:10px;color:#636363;padding-bottom:8px;">
                {% if post.user_id == user %}
                <a href="{% url 'board:delete_post' post.post_id %}" class="btn bg-accent text-white">글 삭제</a>
                <a href="{% url 'board:edit_post' post.post_id %}" class="btn bg-accent text-white">글 수정</a>
                {% endif %}
                <a href="javascript:location.reload()"><span class="style7 btn bg-accent text-white">새로고침</span></a>
                <a onfocus="blur()" href="{% url 'board:board' course_id %}"><span class="style7 btn bg-accent text-white">목록보기</span></a>&nbsp;
            </td>
        </tr>
        </tbody></table>


        <div id="color" style="text-align:center;height:24px;"></div>



        <hr align="center" style="margin-top:12px;margin-bottom:12px;width:970px;border:0;height:1px;background-image:linear-gradient(to right, #eee, #edecec, #eee);">




<!-- 댓글 시작-->
  <div id="comment_container">
    <div id="comment_wrapper">
{% for comment in comment_list %}
<table align="center" border="0" width="970" cellspacing="0" cellpadding="0" style="table-layout:fixed" id="re1" name="re1">
    <tbody>
    <tr>
        <td style="padding:0">
            <table border="0" width="100%" cellspacing="0" cellpadding="0" class="info_bg" style="table-layout:fixed;">
                <tbody>
                <tr valign="top">
                    <td width="100" align="center" style="padding-top:0px;"><img src="{% static "img/hand_pupple.jpg" %}" style="border-radius:48px;border:0;" width="64"></a></td>
                    <td width="5"></td>
                    <td style="padding:1px 0 4px 0px;word-break:break-all" align="left">
                        <span id="cTitle3172967" style="line-height:200%">
                            <span style="color:#333;font-weight:bold;font-size:12px;">{{comment.user_id}}</span>
                            <span class="sm logout">
                                <span style="color:#999999;">{{comment.upload_time}}</span>
                                {% if comment.user_id == user_id %}
                                <button type="submit" class="delete_comment_btn btn" id={{comment.comment_id}} style="font-size:10px;color:#e0210b" >댓글 삭제</button>
                                {% endif %}

                            </span>


                            <table width="700" cellpadding="0" cellspacing="0" id="cid1">
                                <tbody>
                                <tr>
                                    <td align="left" class="hansb " style="word-break:break-word;padding-top:4px;font-size:15px;">
                                        {{comment.comment_content}}<br><p>
                                    </p>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </span>
                    </td>
                </tr>
			</tbody>
            </table>
		 </td>
    </tr>
    <tr>
        <td colspan="2" align="right">
        </td>
    </tr>
    </tbody>
</table>

<hr align="center" style="margin-top:12px;margin-bottom:12px;width:970px;border:0;height:1px;background-image:linear-gradient(to right, #eee, #edecec, #eee);">
{% endfor %}
<!-- 댓글 끝-->



<!-- 댓글쓰기 시작-->
        <table align="center" width="970" cellpadding="0" cellspacing="0" style="border-top:solid 0px #cccccc;background:#fafafa;margin-top:15px;">
            <tbody>
            <tr>
                <td colspan="2" width="100%">
                    <table border="0" cellspacing="0" cellpadding="0" class="info_bg" width="986" style="table-layout:fixed" id="comment_input_container">
                        <tbody>
                        <tr>
                            <td valign="top" style="padding:2px 1px 0 8px;" width="85" align="center">
                                <img src="{% static "img/hand_pupple.jpg" %}" width="64" border="0" class="mids" style="border:0;border-radius:48px;">
                                <br>
                                <a>{{user}}</a>
                            </td>

                            <td align="right" width="780">
                                <table border="0" cellspacing="2" cellpadding="0" width="100%" >
                                    <tbody>
                                    <tr>
                                        <td id="re" name="re">
                                            <textarea name="comment" id="comment_input" cols="20" rows="6" class="textarea roboto" style="font-size:14px;letter-spacing:-0.1px;width:100%;background-color:#fafafa;" editable="0"></textarea>
                                            <div id="output_profile" style="display:inline-block;position:relative;left:0;top:5px;"></div>
                                        </td>
                                        <td width="34" align="center" style="padding:1px 0 1px 0;"></td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <table border="0" cellspacing="2" cellpadding="0" width="100%">
                                                <tbody>
                                                <tr>
                                                    <td align="left" style="padding-top:8px;"><div id="rcvData"></div></td>
                                                    <td width="115" style="line-height:19px;"></td>
                                                    <td width="85" align="right" valign="top">
                                                        <button type="submit" id="submit_comment_btn" class="btn bg-accent text-white" style="width: 120px">댓글 전송</button>
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                        <td>&nbsp;</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td class="info_bg" style="height:20px;"></td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            </tbody>
        </table>
<!-- 댓글쓰기 끝-->



{% endblock %}