user/urls.py
from django.conf.urls import url
from . import views

app_name = 'user'
urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^profile/$', views.view_profile, name='profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
]

yanadok/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('timetable.urls')),
    path('course/', include('course.urls')),
    path('', TemplateView.as_view(template_name='timetable/timetable.html'), name='home'),
    path(r'board/', include('board.urls', namespace='board')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
]

user/models.py
import re

from django.contrib.auth.models import AbstractUser
from django.db import models

from yanadok.exceptions import InvalidArgumentException


class User(AbstractUser):
    UNIVERSITY_CHOICE = (
        ('고려대학교', '고려대학교'),
        ('연세대학교', '연세대학교'),
        ('서울대학교', '서울대학교'),
    )
    nickname = models.CharField(max_length=10, blank=True, null=True)
    university = models.CharField(max_length=20, default="고려대학교", choices=UNIVERSITY_CHOICE)
    duedate = models.DateField(db_column='due_date', null=True)  # Field name made lowercase.

    @staticmethod
    def from_registration_info(body):
        User.__validate_fields(body)
        user = User(email=body['email'],
                    username=body['email'],
                    university=body['university'],
                    first_name=body['name'],
                    nickname=body['nickname'])
        user.set_password(body['password'])
        # user.is_active = False
        return user

    @staticmethod
    def __validate_fields(body):
        for key in ['email', 'university', 'password', 'name', 'nickname']:
            if not body.get(key, False):
                raise InvalidArgumentException('입력되지 않은 필드가 있습니다.')

        if not re.match(r'[^@]+@[^@]+\.[^@]+', body['email']):
            raise InvalidArgumentException('잘못된 이메일 형식입니다.')

        if len(body['password']) < 8:
            raise InvalidArgumentException('비밀번호가 너무 짧습니다.')

        if len(body['nickname']) < 2:
            raise InvalidArgumentException('닉네임이 너무 짧습니다.')

    class Meta:
        db_table = 'user'

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta(UserCreationForm):
        model = User
        fields = ('username', 'first_name', 'last_name', 'nickname', 'email', 'university')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'nickname', 'email')

user/views.py
from django.conf import settings
from django.contrib.auth import login
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.db.utils import IntegrityError
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from user.exceptions import DuplicateUserException
from yanadok.exceptions import BadRequestException, InvalidArgumentException
from .forms import CustomUserChangeForm
from .models import User
from .tokens import account_activation_token


def signup(request):
    if request.method == 'POST':
        body = extract_registration_body(request)

        try:
            check_invalid_signup_request(body)
            user = User.from_registration_info(body)
            user.save()
            return redirect('login')
        except (DuplicateUserException, BadRequestException, InvalidArgumentException) as e:
            return render_with_error_message(request, 'user/signup.html', e.message)

    return render(request, 'user/signup.html')


def check_invalid_signup_request(body):
    if is_user_exists(body['email']):
        raise DuplicateUserException

    if body['password'] != body['password_check']:
        raise BadRequestException('비밀번호를 확인해주세요.')

    return None


def render_with_error_message(request, template, message):
    return render(request, template, {"error": {"message": message}})


def is_user_exists(email):
    return User.objects.filter(email=email).exists()


def extract_registration_body(request):
    return {key: request.POST[key] for key in ['email', 'password', 'password_check', 'university', 'name', 'nickname']}


def login_view(request):
    if request.method == 'POST':
        user = User.objects.filter(email=request.POST['username']).first()
        if not user or not user.check_password(request.POST['password']):
            return render_with_error_message(request,
                                             'user/login.html',
                                             '아이디나 비밀번호가 일치하지 않습니다.')
        login(request, user)
        return redirect('home')

    return render(request, 'user/login.html')


def send_registration_email(request, user):
    current_site = get_current_site(request)
    mail_subject = 'Activate your blog account.'
    message = render_to_string('user/acc_active_email.html', {
        'user': user,
        'domain': settings.EMAIL_AUTH_HOST if settings.EMAIL_AUTH_HOST else 'localhost',
        'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
        'token': account_activation_token.make_token(user),
    })
    email = EmailMessage(
        mail_subject, message, to=[user.email]
    )
    email.send()


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)

    #     usolved problem
    except(TypeError, ValueError, OverflowError, IntegrityError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('home')
    else:
        return HttpResponse('Activation link is invalid!')


def view_profile(request):
    args = {'user': request.user}
    return render(request, 'user/profile.html', args)


def edit_profile(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/user/profile')

    else:
        form = CustomUserChangeForm(instance=request.user)
        args = {'form': form, 'user': request.user}
        return render(request, 'user/edit_profile.html', args)

templates/user/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/user/edit_profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block content %}
<div class = "container">
    <h1>Profile</h1>
    <form method="post">
        {% csrf_token %}



        <table>
            <tr>
                <td>Username: </td>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <td>{{ form.first_name.label_tag }}</td>
                <td>{{ form.first_name }}</td>
                {% for error in form.first_name.errors %}
                <td style="color: red">{{ error }}</td>
                {% endfor %}
            </tr>
            <tr>
                <td>{{ form.last_name.label_tag }}</td>
                <td>{{ form.last_name }}</td>
                {% for error in form.last_name.errors %}
                <td style="color: red">{{ error }}</td>
                {% endfor %}
            </tr>
            <tr>
                <td>{{ form.nickname.label_tag }}</td>
                <td>{{ form.nickname }}</td>
                {% for error in form.nickname.errors %}
                <td style="color: red">{{ error }}</td>
                {% endfor %}
            </tr>
            <tr>
                <td>{{ form.email.label_tag }}</td>
                <td>{{ form.email }}</td>
                {% for error in form.email.errors %}
                <td style="color: red">{{ error }}</td>
                {% endfor %}
            </tr>
            <tr>
                <td>University: </td>
                <td>{{ user.university }}</td>
            </tr>
        </table>




        <button type="submit">Submit</button>
    </form>
    <br>


</div>



{% endblock %}

templates/user/login.html
{% extends "base.html" %}

{% block head %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "user/login.css" %}">
{% endblock %}

{% block content %}


<div class="w-100 h-50 d-flex bg-primary">
    <div class="title">
        <div class="title-img row align-self-center">
            <img src="{% static "img/title.png" %}" width="100%" height="100%"/>
        </div>
        <div class="row text-white font-weight-bold justify-content-end">
            <div class="mt-2">야 너도 할수있어<br/>독강</div>
        </div>
    </div>
</div>
<form method="post" action="{% url 'login' %}">
{% csrf_token %}

<div class="col">
    {% if error %}
    <div class="row justify-content-center alert alert-danger">
        <div>{{ error.message }}</div>
    </div>
    {% endif %}
    <div class="row justify-content-center">
        <input type="text" class="justify-self-center form-text form-control login-input" placeholder="ID" name="username"/>
    </div>
    <div class="row justify-content-center">
        <input type="password" class="justify-self-center form-control login-input" placeholder="PW" name="password"/>
    </div>
    <div class="row justify-content-center container-btn">
        <input type="submit" class="btn btn-primary text-white" value="로그인"/>
        <a href="{% url 'user:signup' %}" class="btn btn-primary text-white">회원가입</a>
        <a href="{% url 'password_reset' %}" class="btn btn-primary text-white">아이디/비밀번호 찾기</a>
    </div>
    <input type="hidden" name="next" value="{{ next }}"/>
</div>
</form>

{% endblock %}

templates/user/profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block content %}
<div class = "container">
    <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Nick name: {{ user.nickname }}</p>
    <p>Email: {{ user.email }}</p>
    <p>University: {{user.university }} </p>
    <a href="edit">edit</a>
</div>



{% endblock %}

templates/user/signup.html
{% extends "base.html" %}


{% block head %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "user/signup.css" %}">
{% endblock %}

{% block content %}
<div class="bg-primary w-100 pb-4">
    <nav class="bg-primary">
        <div class="text-right text-white font-weight-bold p-2">야 너도 할수있어 독강</div>
    </nav>
    <div class="content">
        <div class="title">
            <a href="{% url "login" %}"><img src="{% static "img/title.png" %}" width="100%" height="100%"/></a>
        </div>
        <form method="post" action="{% url 'user:signup' %}">
        {% csrf_token %}
        {% if error %}<div class="alert alert-danger">{{ error.message }}</div>{% endif %}
        <div class="form-group">
            <select name="university" class="signup-input form-control" id="university-select">
                <option>고려대학교</option>
            </select>
        </div>
        <input type="email" name="email" class="signup-input justify-self-center form-text form-control" placeholder="메일주소(학교 도메인)"/>
        <input type="password" name="password" class="signup-input justify-self-center form-text form-control" placeholder="비밀번호"/>
        <input type="password" name="password_check" class="signup-input justify-self-center form-text form-control" placeholder="비밀번호 확인"/>
        <input type="text" name="name" class="signup-input justify-self-center form-text form-control" placeholder="이름"/>
        <input type="text" name="nickname" class="signup-input justify-self-center form-text form-control" placeholder="닉네임"/>
        <div class="row">
            <button type="submit" class="signup-submit btn text-white">회원가입</button>
        </div>
        </form>
    </div>
</div>

{% endblock %}